# Generated by Django 5.2 on 2025-05-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for this change"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.camera",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="camera_history_from",
                        to="facility.unit",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="camera_history_to",
                        to="facility.unit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Camera Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FilterHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for this change"),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.filter",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filter_history_from",
                        to="facility.unit",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filter_history_to",
                        to="facility.unit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Filter Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FilterWheelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for this change"),
                ),
                (
                    "filter_wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.filterwheel",
                    ),
                ),
                (
                    "from_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filterwheel_history_from",
                        to="facility.unit",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filterwheel_history_to",
                        to="facility.unit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Filter Wheel Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
