# Generated by Django 5.2 on 2025-05-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0002_camerahistory_filterhistory_filterwheelhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="last_maintenance",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="next_maintenance",
        ),
        migrations.CreateModel(
            name="Focuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(default="PWI4", max_length=50)),
                ("host_ip", models.CharField(max_length=15)),
                ("port_num", models.CharField(max_length=10)),
                ("device_num", models.IntegerField(default=0)),
                ("min_step", models.IntegerField(default=2000)),
                ("max_step", models.IntegerField(default=14000)),
                ("check_time", models.FloatField(default=0.5)),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focuser",
                        to="facility.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(default="PWI4", max_length=20)),
                ("host_ip", models.CharField(default="10.0.106.6", max_length=15)),
                ("port_num", models.CharField(default="8220", max_length=10)),
                ("device_num", models.IntegerField(default=0)),
                ("park_alt", models.FloatField(default=40.0)),
                ("park_az", models.FloatField(default=300.0)),
                ("rms_ra", models.FloatField(default=0.15)),
                ("rms_dec", models.FloatField(default=0.15)),
                ("check_time", models.FloatField(default=0.5)),
                ("settle_time", models.IntegerField(default=3)),
                (
                    "unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount",
                        to="facility.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset", models.IntegerField(default=999)),
                ("error", models.IntegerField(default=999)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.filter",
                    ),
                ),
                (
                    "filter_wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.filterwheel",
                    ),
                ),
            ],
            options={
                "unique_together": {("filter", "filter_wheel")},
            },
        ),
    ]
