# Generated by Django 5.2 on 2025-05-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0003_remove_camera_last_maintenance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterwheel",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="focuser",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="mount",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unit",
            name="status",
            field=models.CharField(
                choices=[("idle", "Idle"), ("busy", "Busy"), ("offline", "Offline")],
                default="idle",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="status_update_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
