# Generated by Django 5.2 on 2025-05-20 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facility",
            "0004_filterwheel_name_focuser_name_mount_name_unit_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalstatus",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="operationalstatus",
            name="reported_by",
        ),
        migrations.AlterModelOptions(
            name="filterwheel",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="unit",
            name="facility_un_is_acti_8b96c3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="filterposition",
            unique_together={("filter_wheel", "position")},
        ),
        migrations.RemoveField(
            model_name="camera",
            name="fov_a",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="fov_b",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="pixel_scale",
        ),
        migrations.RemoveField(
            model_name="focuser",
            name="check_time",
        ),
        migrations.RemoveField(
            model_name="mount",
            name="check_time",
        ),
        migrations.RemoveField(
            model_name="mount",
            name="rms_dec",
        ),
        migrations.RemoveField(
            model_name="mount",
            name="rms_ra",
        ),
        migrations.RemoveField(
            model_name="mount",
            name="settle_time",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="camera",
            name="byname",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="camera",
            name="gain",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="camera",
            name="unit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camera",
                to="facility.unit",
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="central_wl",
            field=models.FloatField(help_text="Central wavelength in nanometers"),
        ),
        migrations.AlterField(
            model_name="filter",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="filter",
            name="width",
            field=models.FloatField(help_text="Filter bandwidth in nanometers"),
        ),
        migrations.AlterField(
            model_name="filterposition",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="filterwheel",
            name="current_position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filterwheel",
            name="filters",
            field=models.ManyToManyField(
                through="facility.FilterPosition", to="facility.filter"
            ),
        ),
        migrations.AlterField(
            model_name="filterwheel",
            name="unit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter_wheel",
                to="facility.unit",
            ),
        ),
        migrations.AlterField(
            model_name="focuser",
            name="host_ip",
            field=models.CharField(default="10.0.106.6", max_length=15),
        ),
        migrations.AlterField(
            model_name="focuser",
            name="port_num",
            field=models.CharField(default="8220", max_length=10),
        ),
        migrations.DeleteModel(
            name="OperationalStatus",
        ),
    ]
