# Generated by Django 5.2 on 2025-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0005_remove_operationalstatus_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="focuser",
            name="check_time",
            field=models.FloatField(default=0.5),
        ),
    ]
