# Generated by Django 5.2 on 2025-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0006_focuser_check_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True,
                        help_text="Relative humidity in percentage",
                        null=True,
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        blank=True, help_text="Atmospheric pressure in hPa", null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, help_text="Wind speed in m/s", null=True
                    ),
                ),
                (
                    "wind_direction",
                    models.FloatField(
                        blank=True, help_text="Wind direction in degrees", null=True
                    ),
                ),
                (
                    "cloud_cover",
                    models.FloatField(
                        blank=True, help_text="Cloud coverage percentage", null=True
                    ),
                ),
                (
                    "seeing",
                    models.FloatField(
                        blank=True,
                        help_text="Astronomical seeing in arcseconds",
                        null=True,
                    ),
                ),
                (
                    "rain_rate",
                    models.FloatField(
                        blank=True, help_text="Rain rate in mm/hour", null=True
                    ),
                ),
                (
                    "sky_temperature",
                    models.FloatField(
                        blank=True, help_text="Sky temperature in Celsius", null=True
                    ),
                ),
                (
                    "dew_point",
                    models.FloatField(
                        blank=True, help_text="Dew point in Celsius", null=True
                    ),
                ),
                (
                    "ambient_light",
                    models.FloatField(
                        blank=True, help_text="Ambient light level in lux", null=True
                    ),
                ),
                (
                    "safe_status",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if weather conditions are safe for observing",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weather",
                "ordering": ["-timestamp"],
            },
        ),
    ]
