# Generated by Django 5.2 on 2025-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="night",
            name="files_scanned",
            field=models.BooleanField(
                default=False,
                help_text="Whether FITS files have been scanned for this night",
            ),
        ),
        migrations.AddField(
            model_name="night",
            name="scan_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When file scanning completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="night",
            name="scan_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When file scanning started", null=True
            ),
        ),
        migrations.AddField(
            model_name="night",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partial", "Partially Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
