# Generated by Django 5.2 on 2025-06-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey",
            "0003_rename_total_exposure_time_unitstatistics_total_exptime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scienceframe",
            name="object_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIAS", "Bias"),
                    ("DARK", "Dark"),
                    ("FLAT", "Flat"),
                    ("RIS", "RIS"),
                    ("WTS", "WTS"),
                    ("IMS", "IMS"),
                    ("ToO", "Target of Opportunity"),
                    ("target", "General Target"),
                ],
                db_index=True,
                help_text="OBJTYPE - Object classification (TCSpy standard values)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scienceframe",
            name="obsmode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single Mode"),
                    ("Spec", "Spectroscopic Mode"),
                    ("Deep", "Deep Mode"),
                    ("Search", "Search Mode"),
                    ("Color", "Color Mode"),
                ],
                db_index=True,
                help_text="OBSMODE - Observation mode (TCSpy standard values)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scienceframe",
            name="specmode",
            field=models.CharField(
                blank=True,
                choices=[("specall", "All Spectroscopic"), ("", "Not Applicable")],
                help_text="SPECMODE - Spectroscopic mode (when OBSMODE=Spec)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scienceframe",
            name="tile",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated tile for survey observations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="survey.tile",
            ),
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Target designation", max_length=100, unique=True
                    ),
                ),
                ("ra", models.FloatField(help_text="Right Ascension in degrees")),
                ("dec", models.FloatField(help_text="Declination in degrees")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("TOO", "Target of Opportunity"),
                            ("STD", "Standard Star"),
                            ("EXSCI", "Third-Party Science Target"),
                            ("TEST", "Test Target"),
                        ],
                        default="EXSCI",
                        help_text="Type of target",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Target description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="survey_targ_name_3e4400_idx"),
                    models.Index(
                        fields=["ra", "dec"], name="survey_targ_ra_2fc820_idx"
                    ),
                    models.Index(
                        fields=["target_type"], name="survey_targ_target__4837d0_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="scienceframe",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated target for non-survey observations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="survey.target",
            ),
        ),
    ]
