# Generated by Django 5.2 on 2025-06-24 04:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_alter_scienceframe_object_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="area_sq_deg",
            field=models.FloatField(
                blank=True, help_text="Target area in square degrees", null=True
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="associated_tiles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tiles associated with this target (for tile-based observations)",
                to="survey.tile",
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="first_observed",
            field=models.DateField(
                blank=True, help_text="Date first observed", null=True
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="fov_height",
            field=models.FloatField(
                default=1.38, help_text="Field of view height in degrees"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="fov_width",
            field=models.FloatField(
                default=0.92, help_text="Field of view width in degrees"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="last_observed",
            field=models.DateField(
                blank=True, help_text="Date last observed", null=True
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="observation_count",
            field=models.IntegerField(
                default=0, help_text="Total number of science frames"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="observation_strategy",
            field=models.CharField(
                choices=[
                    ("centered", "Target-Centered Observation"),
                    ("tile_based", "Tile-Based Observation"),
                ],
                default="centered",
                help_text="Observation strategy for this target",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="position_angle",
            field=models.FloatField(
                default=0.0, help_text="Position angle in degrees (0=North)"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="total_exposure_time",
            field=models.FloatField(
                default=0, help_text="Total exposure time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="vertices",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, help_text="Target field of view polygon", null=True, srid=0
            ),
        ),
        migrations.AlterField(
            model_name="scienceframe",
            name="object_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIAS", "Bias"),
                    ("DARK", "Dark"),
                    ("FLAT", "Flat"),
                    ("RIS", "RIS"),
                    ("WTS", "WTS"),
                    ("IMS", "IMS"),
                    ("ToO", "ToO"),
                    ("target", "General Target"),
                ],
                db_index=True,
                help_text="OBJTYPE - Object classification (TCSpy standard values)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["observation_strategy"], name="survey_targ_observa_09c8c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["first_observed"], name="survey_targ_first_o_10d54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["last_observed"], name="survey_targ_last_ob_87ebec_idx"
            ),
        ),
    ]
