# Generated by Django 5.2 on 2025-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_target_area_sq_deg_target_associated_tiles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="fov_height",
            field=models.FloatField(
                default=0.92, help_text="Field of view height in degrees"
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="fov_width",
            field=models.FloatField(
                default=1.38, help_text="Field of view width in degrees"
            ),
        ),
    ]
