# Generated by Django 5.2 on 2025-06-24 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_alter_target_fov_height_alter_target_fov_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scienceframe",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated target for non-survey observations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.target",
            ),
        ),
        migrations.AlterField(
            model_name="scienceframe",
            name="tile",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated tile for survey observations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.tile",
            ),
        ),
    ]
