# Generated by Django 5.2 on 2025-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_alter_scienceframe_target_alter_scienceframe_tile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scienceframe",
            name="specmode",
            field=models.CharField(
                blank=True,
                help_text="SPECMODE - Spectroscopic or multi-filter mode (when OBSMODE=Spec or Color)",
                max_length=20,
            ),
        ),
    ]
